### PR TITLE
feat: add main and module to package.json to support some bundlers

### PR DESCRIPTION
**Pull request by arthur-er**

### CODE REVIEW

**Comment by alii** [comment]
Hi, thanks very much for this contribution. There actually is a bigger issue with the exports so I'll merge this and then add another fix, then make a release.

Out of curiosity, which bundler are you using that doesn't support the current exports setup? `main` and `module` are considered older/deprecated.

**Comment by arthur-er** [comment]
I'm using [plasmo](https://github.com/PlasmoHQ) which uses parcel

**Comment by alii** [comment]
Released in [azs@1.2.0](https://www.npmjs.com/package/azs)

This release breaks importing as default/export default, to enable CJS/ESM compat, so please import as a named import:

```ts
import {azs} from 'azs';
```

**Comment by alii** [comment]
> I'm using [plasmo](https://github.com/PlasmoHQ) which uses parcel

Interesting, Parcel should support these exports just fine. What's the actual error you saw before?

**Pull request merged**
